# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('weight', models.FloatField(default=2)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('metal', models.CharField(max_length=30)),
                ('weight', models.FloatField(default=5.64)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('pyrolysis_temperature', models.IntegerField(default=1400)),
                ('pyrolysis_duration', models.IntegerField(default=2)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
                ('anode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Anode')),
            ],
        ),
        migrations.CreateModel(
            name='Electrolyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('salt', models.CharField(default='NaF6', max_length=30)),
                ('solvent', models.CharField(default='EC:DMC', max_length=30)),
                ('comments', models.TextField(default='Leave your comments here')),
                ('status', models.CharField(choices=[('a', 'Available'), ('n', 'Used')], default='a', max_length=1)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30)),
                ('result', models.FileField(default='none', upload_to='uploads/%Y/%m/%d/')),
                ('comments', models.TextField(default='Leave your comments here')),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='electrolyte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Electrolyte'),
        ),
        migrations.AddField(
            model_name='bag',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Base'),
        ),
        migrations.AddField(
            model_name='bag',
            name='binder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Binder'),
        ),
        migrations.AddField(
            model_name='bag',
            name='carbon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Carbon'),
        ),
        migrations.AddField(
            model_name='anode',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.Bag'),
        ),
    ]
